appointments/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('patient.urls')),
]

patient/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .import views

urlpatterns = [
    path('', views.PersonListView.as_view(), name='patient_changelist'),
    # path('add/', views.PersonCreateView.as_view(), name='patient_add'),
    
    path('<int:pk>/', views.PersonUpdateView.as_view(), name='patient_change'),
    path('add/', views.createAppointment, name="patient_add"),
    path('ajax/load-specialists/', views.load_specialists, name='ajax_load_cities'),
    path('success/', views.success, name='success')
    
]

patient/models.py
from django.db import models
from django.db.models.enums import Choices
from django.contrib.auth.models import User

class Hospital(models.Model):
    name = models.CharField(max_length=200)
    user = models.OneToOneField(User,null=True, blank=True, on_delete=models.CASCADE)
    phone = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=True)
    location    = models.CharField(max_length=40,null=True, blank=True)
    profile_pic = models.ImageField(default='default.png',upload_to='profile_pics')
    is_verified = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return self.name
    
class Specialist(models.Model):
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    specialist = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True)
    
    def __str__(self):
        return self.name

class Appointment(models.Model):
    GENDER = (
        ('Male','male'),
        ('Female','female')
    )
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    gender = models.CharField(max_length=200, choices=GENDER)
    hospital = models.ForeignKey(Hospital, on_delete=models.SET_NULL, null=True)
    specialist = models.ForeignKey(Specialist, on_delete=models.SET_NULL, null=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    message = models.TextField()
    app_date = models.DateField()
        
    def __str__(self):
        return self.first_name

patient/forms.py
from django import forms
from .models import Appointment, Specialist, Hospital

class DateInput(forms.DateInput):
    input_type = 'date'

class AppointmentBookForm(forms.ModelForm):
    app_date = forms.DateField(widget=DateInput)
    
    class Meta:
        model = Appointment
        fields = '__all__'
        widgets = {'app_date' : DateInput()}
        
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['specialist'].queryset = Specialist.objects.none()
        
        if 'hospital' in self.data:
            try:
                hospital_id = int(self.data.get('hospital'))
                self.fields['specialist'].queryset = Specialist.objects.filter(hospital_id=hospital_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['specialist'].queryset = self.instance.hospital.specialist_set.order_by('name')

patient/views.py
from django.shortcuts import render, redirect
from .models import *
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from .forms import AppointmentBookForm
from .tasks import send_sms, appointment_created, checkout
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail

class PersonListView(ListView):
    model = Appointment
    context_object_name = 'appointment'
    template_name = 'patient_list.html'
    
def createAppointment(request):
    if request.method == 'POST':
        form = AppointmentBookForm(request.POST, None)
        
        if form.is_valid():
            form.save()
            email_subject = f'New Appointment: {form.cleaned_data["first_name"]}: {form.cleaned_data["location"]}'
            email_message = f'{form.cleaned_data["first_name"]}, from {form.cleaned_data["location"]}, phone {form.cleaned_data["phone"]} \n\n' \
                            f'requests an appointment.' \
                            f'with {form.cleaned_data["specialist"]} on {form.cleaned_data["app_date"]}'
            send_mail(email_subject, email_message, settings.CONTACT_EMAIL, settings.ADMIN_EMAIL)
            # id = form.cleaned_data['id']
            # first_name = form.cleaned_data['first_name']
            # last_name = form.cleaned_data['last_name']
            # gender = form.cleaned_data['gender']
            # phone = form.cleaned_data['phone']
            # location = form.cleaned_data['location']
            # hospital = form.cleaned_data['hospital']
            # specialist = form.cleaned_data['specialist']
            # message = form.cleaned_data['message']
            # app_date = form.cleaned_data['app_date']
        
            # appointment = checkout(request, id, first_name, last_name, gender, location, hospital, specialist, app_date, message, phone)
            # appointment_created(appointment)
            return render(request, 'success.html')
    
    form = AppointmentBookForm()
    return render(request, 'patient_form.html',{'form': form})
class PersonCreateView(CreateView):
    model = Appointment
    fields = ('first_name', 'last_name', 'gender', 'location', 'hospital', 'specialist','phone', 'message', 'app_date')
    success_url = reverse_lazy('patient_changelist')
    template_name = 'patient_form.html'
    
class PersonUpdateView(UpdateView):
    model = Appointment
    ffields = ('first_name', 'last_name', 'gender', 'location', 'hospital', 'specialist','phone', 'message', 'app_date')
    success_url = reverse_lazy('person_changelist')
    template_name = 'patient_form.html'

def load_specialists(request):
    hospital_id = request.GET.get('hospital')
    specialists = Specialist.objects.filter(hospital_id=hospital_id).order_by('name')
    return render(request, 'city_dropdown_list_options.html', {'specialists': specialists})

def success(request):
    return render(request, 'success.html')

patient/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    
    <title>Appointment App</title>

</head>
<body>

    <div class="container">
    {% block content %}

    {% endblock %}

    </div>

</body>
</html>

patient/templates/city_dropdown_list_options.html
{% extends 'base.html' %}

{% block content %}

<option value="">---------</option>
{% for specialist in specialists %}
<option value="{{ specialist.pk }}">{{ specialist.name }}</option>
{% endfor %}

{% endblock %}

patient/templates/patient_form.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <title>Appointment App</title>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Login</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  <main role="main" class="container">
    <div class="row justify-content-center">
      {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
      <div class="col-md-8">
<h2 style="color: rgb(108, 141, 202);font-weight: bolder;text-align: center;">Meet your Doctor Today</h2>
<form method="POST" id="AppointmentBookForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-4 mb-0">
        {{ form.first_name|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.last_name|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.gender|as_crispy_field }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ form.phone|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ form.location|as_crispy_field }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4 mb-0">
        {{ form.hospital|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.specialist|as_crispy_field }}
      </div>
      <div class="form-group col-md-4 mb-0">
        {{ form.app_date|as_crispy_field }}
      </div>
    </div>
    {{ form.message|as_crispy_field }}
    <button type="submit" class="btn btn-primary">Book Now</button>
</form>
    
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_hospital").change(function () {
      var url = $("#AppointmentBookForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var hospitalId = $(this).val();  // get the selected country ID from the HTML input
  
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'hospital': hospitalId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_specialist").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });
  
    });
  </script>



</div>



  </main>

</body>
</html>

patient/templates/patient_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Human Resources Module</title>
</head>
<body>

    <h2>Human Resources Module » People Management</h2>

  <div class="row">

    <div class="col s10">

  <p>
    <a class="waves-effect waves-light btn" href="{% url 'patient_add' %}">Add Patient</a>
    
  </p>

  <table border="1" class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Location</th>
        <th>Gender</th>
        <th>Hospital</th>
        <th>Specialist</th>
        <th>Appointment Day</th>
      </tr>
    </thead>
    <tbody>
      {% for person in appointment %}
        <tr>
          <td><a href="">{{ person.get_full_name }}</a></td>
          <td>{{ person.first_name }}</td>
          <td>{{ person.last_name }}</td>
          <td>{{ person.location }}</td>
          <td>{{ person.gender }}</td>
          <td>{{ person.hospital.name }}</td>
          <td>{{ person.specialist.name }}</td>
          <td>{{ person.app_date }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No person in the database. <a href="{% url 'patient_add' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
    </div>
  </div>

    
</body>
</html>
  

patient/templates/success.html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Success</h1> 
        <p>We have received your appointment request;<br/> we'll be in touch shortly!</p>
        <a button class="btn" href="/">Homepage</button>
      </div>
    </body>
</html>